# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/aspnet-mvc"

destination: _site-mvc

# Exclude files which should not be in the output
exclude: [README.md,
Gemfile,
Gemfile.lock,
api_sort.rb,
Dockerfile,
bs-config.js,
build-docs.sh,
copy_content.sh,
copy_local.sh,
docs-watcher/*,
exclude_files.txt,
install-npm.sh,
start-docs.sh,
watch.sh,
migration/*,
tutorials/tutorial-kendo-music-store/*,
tutorials/tutorial-saleshub/*,
tag-helpers/*,
getting-started-core/*,
backwards-compatibility/2018-backwards-compatibility.md,
knowledge-base/checkbox-list-post.md,
knowledge-base/daterangepicker-bind-to-model-and-post.md,
knowledge-base/daterangepicker-messages-input-text-change.md,
knowledge-base/form-in-strongly-typed-view.md,
knowledge-base/grid-add-new-button-header-inline.md,
knowledge-base/grid-ajax-binding.md,
knowledge-base/grid-ajax-editing.md,
knowledge-base/grid-bind-a-dropdownlist-editor.md,
knowledge-base/grid-custom-datasource-razor-pages.md,
knowledge-base/grid-custom-datasource.md,
knowledge-base/grid-enable-operations-for-object-column.md,
knowledge-base/grid-header-multicolumn-title-change.md,
knowledge-base/grid-icon-command-button-no-text.md,
knowledge-base/grid-is-not-showing-data.md,
knowledge-base/grid-listbox-as-editor.md,
knowledge-base/grid-multiselect-as-editor.md,
knowledge-base/grid-norecords-template-controller-server-viewdata.md,
knowledge-base/grid-page-size-all.md,
knowledge-base/grid-remove-spinner-numerictextbox-editor.md,
knowledge-base/invalid-template-error-when-using-localization.md,
knowledge-base/multiselect-post-data-values.md,
knowledge-base/scheduler-sql-server-database.md,
knowledge-base/setup-private-nuget-feed-azure.md,
knowledge-base/treelist-checkbox-column.md,
knowledge-base/upload-resize-image-before-upload.md,
knowledge-base/validator-basic-form-validation.md,
knowledge-base/vs-online-continuous-integration-login-problem.md]

exclude_navigation: ["knowledge-base/*",
api/Kendo.Mvc/*,
api/Kendo.Mvc.UI/*,
api/Kendo.Mvc.UI.Fluent/*,
asp-net-mvc-3.html,
asp-net-mvc-4.html,
getting-started-mvc/*]

## The application virtual path
baseurl: /aspnet-mvc

ff-sheet-id: 17DDhsKyPUgO6GlvL8WEfCCN6tikyInp4qpRGCvvs794

## Product
product_long: "Progress Telerik UI for ASP.NET MVC"
product: "Telerik UI for ASP.NET MVC"
product_short: "UI for ASP.NET MVC"
framework: "ASP.NET MVC"
framework_short: "MVC"
platform: aspnet-mvc

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        product: "aspnet-mvc"
        editable: true
-
    scope:
        path: "aspnet-mvc"
    values:
        product: "aspnet-mvc"

    scope:
        path: "api"
    values:
        editable: false
        res_type: api
        kind: api

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# The google services configuration
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:rdwxfmavt8o'
gcs_api_key: 'AIzaSyDnvT29LoZiLUcywskEgTTum7j5pkx6s8I'

core: false
mvc: true

footer:
-
  title: "Getting Started"
  links:
    "Getting Started": https://docs.telerik.com/aspnet-mvc/getting-started/first-steps
    "Demos": https://demos.telerik.com/aspnet-mvc/
    "Sample Applications": https://demos.telerik.com/aspnet-mvc/
-
  title: "Support Resources"
  links:
    "Knowledge Base": https://docs.telerik.com/aspnet-mvc/knowledge-base
-
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/aspnet-mvc
    "Blogs": https://www.telerik.com/blogs/.net
    "Feedback Portal": https://feedback.telerik.com/aspnet-mvc


download: http://www.telerik.com/download/aspnet-mvc
